name: Download and Extract KS Wings

on:
  workflow_dispatch:    # Also runs when you push to main

permissions:
  contents: write      # Required to push files

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download ks-wings.zip
        run: |
          wget https://github.com/kswarrior/ks-wings/releases/download/ks-wings/ks-wings.zip -O ks-wings.zip

      - name: Unzip ks-wings
        run: |
          unzip ks-wings.zip
          ls -la
          ls -la ks-wings

      - name: Copy Files to Repository Root
        run: |
          cp -r ks-wings/* .
          rm -rf ks-wings ks-wings.zip

      - name: Commit and Push Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto upload ks-wings files from release"
          git push
